config/routes.rb
Querl::Application.routes.draw do
  resources :targets

  resources :target_lists

  resources :responses do
    collection do
      get 'export'
      get 'reports'
    end
  end

  resources :survey_items do
    collection do
      get 'add_to_survey'
    end
  end

  resources :user_roles

  resources :projects do
    collection do
      get 'show_users'
      get 'remove_user'
      get 'add_owner'
      get 'add_coder'
    end
  end
  resources :surveys do
    collection do
      get 'gather_response'
      get 'remove_survey_item'
      get 'preview'
      get 'move'
      get 'clone'
    end
  end
  
  resources :targets do
    collection do
      post 'import'
    end
  end

  devise_for :users

  root 'dashboard#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    
    user ||= User.new # guest user
    
    can :manage, :all
  
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_many :surveys, dependent: :destroy
  has_many :user_roles, dependent: :destroy
  has_many :users, through: :user_roles
  has_many :survey_items, dependent: :destroy
  has_many :target_lists, dependent: :destroy
  
  def get_role(user)
    unless user.user_roles.where(:project_id => self.id)[0].nil? 
      user.user_roles.where(:project_id => self.id)[0].name
    end  
  end  
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :user
  belongs_to :survey
  belongs_to :survey_item
  belongs_to :target
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :project
  has_and_belongs_to_many :survey_items, -> { order('survey_items_surveys.position') }
  has_many :responses
  belongs_to :target_list
  has_many :target_pools, -> { order('target_id') }
  
  def next_target(user)
    nxttar = ""
    behavior = self.behavior
    completed_targets = Array.new
    locked_target = self.target_pools.where(:user_id => user.id, :locked => true, :completed => false)
    
    if behavior == "Unicode (targets do not repeat across coders)"
      all_locked = Array.new
      self.target_pools.where(:locked => true, :completed => false).collect {|pool| all_locked << pool.target_id }
      self.target_pools.where(:locked => true, :completed => true).collect {|pool| completed_targets << pool.target_id }
    elsif behavior == "Multicode (all coders get all targets)"
      self.target_pools.where(:user_id => user.id, :locked => true, :completed => true).collect {|pool| completed_targets << pool.target_id }
    end  
    
    if self.target_pools.empty?
      TargetPool.create(:user_id => user.id, :target_id => self.target_list.targets.first.id, :survey_id => self.id, :locked => true, :completed => false)
      return self.target_list.targets.first
    elsif !locked_target[0].nil? 
      return Target.find(locked_target[0].target_id)  
    else  
      self.target_list.targets.each do |target|
        unless completed_targets.include?(target.id) || (!all_locked.nil? && all_locked.include?(target.id))
          nxttar = target
        end  
      end
      unless nxttar == ""
        TargetPool.create(:user_id => user.id, :target_id => nxttar.id, :survey_id => self.id, :locked => true, :completed => false)
      end  
      return nxttar  
    end  
  end 
  
  def clone_with_associations
      new_survey = self.dup
      new_survey.target_list = nil
      new_survey.behavior = nil
      new_survey.save
      #simple association
      new_survey.project = self.project
      new_survey.survey_items = self.survey_items
      new_survey
    end 
end

app/models/survey_item.rb
class SurveyItem < ActiveRecord::Base
  
  has_and_belongs_to_many :surveys
  has_many :responses
  belongs_to :project
  
  validates_presence_of :field_name, :field_type
  validates_uniqueness_of :field_name
  validates_format_of :field_name, :with => /^\S+\w{2,32}\S{1,}/, :multiline => true, :message => "cannot contain spaces or special characters"
  
  FIELD_TYPES = ['Checkbox', 'Dropdown', 'File', 'Radio', 'String (Text box)', 'Textarea (Paragraph)', 'Date', 'Label' ]
  FIELD_OPTIONS = ['']
  
  def to_s
    self.field_name
  end  
  
  def formtastic_field_map
    as_param = ""
    if self.field_type == "Checkbox"
      as_param = "check_boxes"  
    elsif self.field_type == "Dropdown"
      as_param = "select"
    elsif self.field_type == "File"
      as_param = "file"
    elsif self.field_type == "Radio"
      as_param = "radio"
    elsif self.field_type == "String (Text box)"
      as_param = "string"
    elsif self.field_type == "Textarea (Paragraph)"
      as_param = "text"
    elsif self.field_type == "Date"
      as_param = "date_select"  
    end            
  end 
end

app/models/survey_items_surveys.rb
class SurveyItemsSurveys < ActiveRecord::Base
  
  belongs_to :survey_item
  belongs_to :survey
  
  acts_as_list :scope => :survey
end

app/models/target.rb
class Target < ActiveRecord::Base
  
  belongs_to :target_list
  has_many :target_pools
  has_many :responses
end

app/models/target_list.rb
class TargetList < ActiveRecord::Base
  
  belongs_to :project
  has_many :targets, -> { order('id') }, dependent: :destroy
  has_one :survey
end

app/models/target_pool.rb
class TargetPool < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :survey
  belongs_to :target
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :user_roles
  has_many :projects, through: :user_roles
  has_many :responses
  has_many :target_pools
  
  ROLES = %w[owner coder]
  
  def get_role(project)
    self.user_roles.where(:project_id => project.id)[0].name
  end 
end

app/models/user_role.rb
class UserRole < ActiveRecord::Base
  
  belongs_to :project
  belongs_to :user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/survey_items_helper.rb
module SurveyItemsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/target_lists_helper.rb
module TargetListsHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/layouts/_footer.html.erb
<p>Copyright© 2014 The President and Fellows of Harvard College</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
	  <a href="../" class="navbar-brand">Querl</a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
  <li><%= link_to 'Dashboard', root_path %></li>
<% if current_user.nil? %>
  <li><%= link_to "Sign In/Sign Up", new_user_session_path %></li>
<% else %>  
  <li><%= link_to "Edit Account", edit_user_registration_path %></li>
  <li><%= link_to "Sign Out (#{current_user.username})", destroy_user_session_path, :method => :delete %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Querl" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Querl" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    
      <%= render 'layouts/navigation' %>
    
    <div class="container">
      <div class="page-header" id="banner">
		  <div class="row">
	        <%= render 'layouts/messages' %>
			<%= breadcrumbs pretext: "You are here: ", separator: " &rsaquo; " %>
	        <%= yield %>
		  </div>	  
      </div>
    
	  <footer>
	    <div class="row">
	          <div class="col-lg-12">
                <%= render 'layouts/footer' %>
	          </div>
	        </div>
        
	  </footer>
	</div>
  </body>
</html>

app/views/shared/_project.html.erb
<div class="table-responsive">
  <table class="table table-striped table-hover ">
	  <tr>
	    <th>Name</th>
		<th>Actions</th>
	  </tr>
	  <% projects.each do |project| %>
	  <tr>
	    <td><%= project.name %></td>
		<% if project.get_role(current_user) == 'owner' %>
	      <td><%= link_to 'Show Users', show_users_projects_path(:id => project.id) %> | <%= link_to 'View Surveys', project_path(project) %> | <%= link_to 'Rename', edit_project_path(project) %> | <%= link_to('Delete', project_path(project), :confirm => "Are you sure? This action cannot be undone.", :method => :delete) %></td>
		<% elsif project.get_role(current_user) == 'coder' %>
		  <td><%= link_to 'View Surveys', project_path(project) %></td>
		<% else %>
		  <td>You are not associated with this project.</td>
		<% end %>  
	  </tr>
	  <% end %>
  </table>
</div>  
 

app/views/shared/forms/_project.html.erb
<%= semantic_form_for @project, :html => { :class => "form-horizontal"} do |f| %>
  <fieldset>
    <legend><%= @project.name %></legend>	    
		<%= f.inputs do %>
		  <div class="form-group"> 
		    <label for="name" class="col-lg-2 control-label">Name</label>
		    <div class="col-lg-10">
		      <%= f.input :name, :label => false, :input_html => { :class => "form-control"} %>
		    </div>	
		  </div>
		  <div class="form-group">
		    <label for="description" class="col-lg-2 control-label">Description</label>
		    <div class="col-lg-10">
		      <%= f.input :description, :label => false, :input_html => { :class => "form-control"} %>
	        </div>
		  </div>
		<% end %>
		<%= f.actions do %>
		  <%= f.action :submit, :as => :button, :button_html => { :class => "btn btn-primary"} %>
		<% end %>
  </fieldset>	
<% end %>

app/views/shared/forms/_survey.html.erb
<%= semantic_form_for @survey, :html => { :class => "form-horizontal"} do |f| %>
  <fieldset>
    <legend><%= @survey.name %></legend>	    
		<%= f.inputs do %>
		  <%= f.input :project_id, :as => :hidden, :input_html => { :value => @project.id} %>
		  <div class="form-group"> 
		    <label for="name" class="col-lg-2 control-label">Name</label>
		    <div class="col-lg-10">
		      <%= f.input :name, :label => false, :input_html => { :class => "form-control"} %>
		    </div>	
		  </div>
		  <div class="form-group">
		    <label for="description" class="col-lg-2 control-label">Description</label>
		    <div class="col-lg-10">
		      <%= f.input :description, :label => false, :input_html => { :class => "form-control"} %>
	        </div>
		  </div>
		<% end %>
		<%= f.actions do %>
		  <%= f.action :submit, :as => :button, :button_html => { :class => "btn btn-primary"} %>
		<% end %>
  </fieldset>	
<% end %>

app/views/shared/forms/_survey_item.html.erb
<%= semantic_form_for @survey_item, :html => { :class => "form-horizontal"} do |f| %>
  <fieldset>
    <legend>Survey Item</legend>	    
		<%= f.inputs do %>
		  <%= f.input :project_id, :as => :hidden, :input_html => { :value => @project.id} %>
		  <div class="form-group"> 
		    <label for="name" class="col-lg-2 control-label">Field Name</label>
		    <div class="col-lg-10">
		      <%= f.input :field_name, :label => false, :input_html => { :class => "form-control"} %>
		    </div>	
		  </div>
		  <div class="form-group">
		    <label for="description" class="col-lg-2 control-label">Display Text</label>
		    <div class="col-lg-10">
		      <%= f.input :display_text, :as => :ckeditor, :label => false, :input_html => { :class => "form-control"} %>
	        </div>
		  </div>
		  <div class="form-group">
		    <label for="description" class="col-lg-2 control-label">Field Type</label>
		    <div class="col-lg-10">
			  <div class="radio">	
		        <%= f.input :field_type, :as => :radio, :collection => SurveyItem::FIELD_TYPES, :label => false %>
			  </div>	
	        </div>
		  </div>
		  <div class="form-group">
		    <label for="description" class="col-lg-2 control-label">Field Options</label>
		    <div class="col-lg-10">
		      <%= f.input :field_options, :label => false, :input_html => { :class => "form-control"}, :hint => "Required for Checkbox, Dropdown, and Radio field types. Use commas with no spaces in between the values to separate the options you want to display. (For example: a,b,c,d)." %>
	        </div>
		  </div>
		  <div class="form-group">
		    <label for="description" class="col-lg-2 control-label">Required Field?</label>
		    <div class="col-lg-10">
		      <%= f.input :required, :as => :boolean, :label => false %>
	        </div>
		  </div>
		<% end %>
		<%= f.actions do %>
		  <%= f.action :submit, :as => :button, :button_html => { :class => "btn btn-primary"} %>
		<% end %>
  </fieldset>
<% end %>

app/views/shared/forms/_target_list.html.erb
<%= semantic_form_for @target_list, :html => { :class => "form-horizontal"} do |f| %>
  <fieldset>
    <legend><%= @target_list.name %></legend>	    
		<%= f.inputs do %>
		  <%= f.input :project_id, :as => :hidden, :input_html => { :value => @project.id} %>
		  <div class="form-group"> 
		    <label for="name" class="col-lg-2 control-label">Name</label>
		    <div class="col-lg-10">
		      <%= f.input :name, :label => false, :input_html => { :class => "form-control"} %>
		    </div>	
		  </div>
		  <div class="form-group">
		    <label for="description" class="col-lg-2 control-label">Description</label>
		    <div class="col-lg-10">
		      <%= f.input :description, :label => false, :input_html => { :class => "form-control"} %>
	        </div>
		  </div>
		<% end %>
		<%= f.actions do %>
		  <%= f.action :submit, :as => :button, :button_html => { :class => "btn btn-primary"} %>
		<% end %>
  </fieldset>	
<% end %>