config/routes.rb
Querl::Application.routes.draw do
  resources :targets

  resources :target_lists

  resources :responses do
    collection do
      get 'export'
      get 'reports'
    end
  end

  resources :survey_items do
    collection do
      get 'add_to_survey'
    end
  end

  resources :user_roles

  resources :projects do
    collection do
      get 'show_users'
      get 'remove_user'
      get 'add_owner'
      get 'add_coder'
    end
  end
  resources :surveys do
    collection do
      get 'gather_response'
      get 'remove_survey_item'
      get 'preview'
      get 'move'
      get 'clone'
    end
  end
  
  resources :targets do
    collection do
      post 'import'
    end
  end

  devise_for :users

  root 'dashboard#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  
  has_many :surveys, dependent: :destroy
  has_many :user_roles, dependent: :destroy
  has_many :users, through: :user_roles
  has_many :survey_items, dependent: :destroy
  has_many :target_lists, dependent: :destroy
  
  def get_role(user)
    unless user.user_roles.where(:project_id => self.id)[0].nil? 
      user.user_roles.where(:project_id => self.id)[0].name
    end  
  end  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  
  def index
    
  end
  
  def show
    @surveys = @project.surveys
    @survey_items = @project.survey_items
    @target_lists = @project.target_lists
  end  
  
  def new
    @project = Project.new
  end
  
  def edit
    
  end
  
  def create
    @project = Project.new(project_params)
    @project.user_roles = [UserRole.create(:user_id => current_user.id, :name => "owner")]
    respond_to do |format|
      if @project.save
        format.html { redirect_to root_url, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, author: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @project = Project.find(params[:id])
    
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to root_url, notice: 'Project was successfully updated.' }
        format.json { head :no_content }  
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show_users
    @current_users = @project.users
    @all_users = User.all
  end
  
  def remove_user
    @project = Project.find(params[:project_id])
    @user = User.find(params[:user_id])
    @role = UserRole.find(:first, :conditions => {:project_id => @project.id, :user_id => @user.id})
    @role.destroy
    redirect_to show_users_projects_url(:id => @project.id)
  end
  
  def add_owner
    @project = Project.find(params[:project_id])
    @user = User.find(params[:user_id])
    @project.user_roles << [UserRole.create(:user_id => @user.id, :name => "owner")]
    redirect_to show_users_projects_url(:id => @project.id)
  end
  
  def add_coder
    @project = Project.find(params[:project_id])
    @user = User.find(params[:user_id])
    @project.user_roles << [UserRole.create(:user_id => @user.id, :name => "coder")]
    redirect_to show_users_projects_url(:id => @project.id)
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit!
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/edit.html.erb
<h2>Edit Project</h2>
<%= render :partial => 'shared/forms/project' %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<div>
  	<table id="projects-table" class="table table-condensed tablesorter">
	<thead>
	  <tr>
		<th>Name</th>
		<th>Actions</th>
	  </tr>
	</thead> 
	<tbody>
	    <% @projects.each do |project| %>
	    	<tr>
	  	  <td><%= project.name %></td>
		  <td>
	   		<%= link_to('Edit', edit_project_path(project), :class => "action-edit") %> | <%= link_to('Delete', project_path(project), :confirm => "Are you sure? This action cannot be undone.", :method => :delete) %>
		  </td>
	    </tr>
	    <% end %>
	</tbody>	
	</table>
	
</div>

app/views/projects/manage_users.html.erb
<h1><%= @project.name %></h1>
<div class="col-lg-6">
  <h2>Current Users</h2>	
  <div class="table-responsive">
    <table class="table table-striped table-hover ">
	  <tr>
	    <th>Name</th>
		<th>Role</th>
		<th>Actions</th>
	  </tr>
	  <% @current_users.each do |user| %>
	  <tr>
	    <td><%= user.username %></td>
		<td><%= user.user_roles.first.name %></td>
	    <td><%= link_to 'Remove from Project', manage_users_projects_path(:id => @project.id) %></td>
	  </tr>
	  <% end %>
    </table>
  </div> 
</div>

<div class="col-lg-6">
  <h2>All Users</h2>
  <div class="table-responsive">
    <table class="table table-striped table-hover ">
	  <tr>
	    <th>Name</th>
		<th>Actions</th>
	  </tr>
	  <% @all_users.each do |user| %>
	  <tr>
	    <td><%= user.username %></td>
	    <td><%= link_to 'Add as Owner', manage_users_projects_path(:id => @project.id) %></td> | <td><%= link_to 'Add as Coder', manage_users_projects_path(:id => @project.id) %></td>
	  </tr>
	  <% end %>
    </table>
  </div>
</div> 
 

app/views/projects/new.html.erb
<div class="col-lg-12">
  <h2>New Project</h2>
  <div class="row">
    <div class="well">
	  <%= render :partial => 'shared/forms/project' %>
    </div>
  </div>	
</div>

app/views/projects/show.html.erb
<% breadcrumb :project, @project %>

<h1>Project: <%= @project.name %></h1>
<div class="col-lg-12">
  <h2>Current Surveys</h2>	
  <p> <%= link_to "Create New Survey", new_survey_path(:project_id => @project.id) %> </p>
  <div class="table-responsive">
    <table class="table table-striped table-hover ">
	  <tr>
	    <th>Name</th>
		<th>Description</th>
		<th>Actions</th>
	  </tr>
	  <% @surveys.each do |survey| %>
	  <tr>
	    <td><%= survey.name %></td>
		<td><%= survey.description %></td>
		<% if @project.get_role(current_user) == 'owner' %>
	      <td><%= link_to 'Preview', preview_surveys_path(:id => survey.id) %> | <%= link_to 'Edit Survey', survey_path(survey) %> | <%= link_to 'Clone', clone_surveys_path(:survey_id => survey.id) %> | <%= link_to 'Begin Coding', survey_path(survey, :owner_code => true) %> | <%= link_to 'Reports', reports_responses_path(:survey_id => survey.id) %> | <%= link_to('Delete', survey_path(survey), :confirm => "Are you sure? This action cannot be undone.", :method => :delete) %></td>
		<% elsif @project.get_role(current_user) == 'coder' %>
		  <td><%= link_to 'Begin Coding', survey_path(survey) %></td>
		<% else %>
		  <td>You are not associated with this project.</td>
		<% end %>
	  </tr>
	  <% end %>
    </table>
  </div> 
</div>

<% if @project.get_role(current_user) == 'owner' %>

<div class="col-lg-6">
  <h2>Available Survey Items</h2>
  <p><%= link_to "Add New Survey Item", new_survey_item_path(:project_id => @project.id) %></p>
  <div class="table-responsive">
    <table class="table table-striped table-hover ">
	  <tr>
	    <th>Field Name</th>
		<th>Display Text</th>
		<th>Actions</th>
	  </tr>
	  <% @survey_items.each do |item| %>
	  <tr>
	    <td><%= item.field_name %></td>
		<td><%= item.display_text %></td>
		<% if @project.get_role(current_user) == 'owner' %>
	      <td><%= link_to('Preview', survey_item_path(item, :project_id => @project.id), :class => "action-view") %> | <%= link_to('Edit', edit_survey_item_path(item), :class => "action-edit") %> | <%= link_to('Clone', new_survey_item_path(:project_id => @project.id, :clone => item.id), :class => "action-edit") %> | <%= link_to('Delete', survey_item_path(item), :confirm => "Are you sure? This action cannot be undone.", :method => :delete) %></td>
		<% else %>
		  <td>You are not associated with this project.</td>
		<% end %>
	  </tr>
	  <% end %>
    </table>
  </div>
</div>

<div class="col-lg-6">
  <h2>Available Target Lists</h2>
  <p><%= link_to "Add New Target List", new_target_list_path(:project_id => @project.id) %></p>
  <div class="table-responsive">
    <table class="table table-striped table-hover ">
    <tr>
      <th>Name</th>
      <th>Description</th>
  	  <th>Actions</th>
  	</tr>
  	<% @target_lists.each do |list| %>
  	<tr>
  	  <td><%= list.name %></td>
  	  <td><%= list.description %></td>
  	  <% if @project.get_role(current_user) == 'owner' %>
  	    <td><%= link_to('Create and Edit Target List', target_list_path(list, :project_id => @project.id), :class => "action-view") %> | <%= link_to('Delete', target_list_path(list), :confirm => "Are you sure? This action cannot be undone.", :method => :delete) %></td>
  	  <% else %>
  	    <td>You are not associated with this project.</td>
  	  <% end %>
  	  </tr>
  	<% end %>
    </table>
  </div>
</div>
<% end %>

app/views/projects/show_users.html.erb
<% breadcrumb :project, @project %>

<h1><%= @project.name %></h1>
<div class="col-lg-6">
  <h2>Current Users</h2>	
  <div class="table-responsive">
    <table class="table table-striped table-hover ">
	  <tr>
	    <th>Name</th>
		<th>Role</th>
		<th>Actions</th>
	  </tr>
	  <% @current_users.each do |user| %>
	  <tr>
	    <td><%= user.username %></td>
		<td><%= user.get_role(@project) %></td>
	    <td>
		  <% unless user == current_user %>
		    <%= link_to 'Remove from Project', remove_user_projects_path(:project_id => @project.id, :user_id => user.id), :confirm => "Are you sure? This action cannot be undone." %>
		  <% end %>  
		</td>  
	  </tr>
	  <% end %>
    </table>
  </div> 
</div>

<div class="col-lg-6">
  <h2>All Users Not Already Added</h2>
  <div class="table-responsive">
    <table class="table table-striped table-hover ">
	  <tr>
	    <th>Name</th>
		<th>Actions</th>
	  </tr>
	  <% @all_users.each do |user| %>
	    <% unless @current_users.include?(user) %>
	      <tr>
	        <td><%= user.username %></td>
	        <td><%= link_to 'Add as Owner', add_owner_projects_path(:project_id => @project.id, :user_id => user.id) %> | <%= link_to 'Add as Coder', add_coder_projects_path(:project_id => @project.id, :user_id => user.id) %></td>
	      </tr>
	    <% end %>	
	  <% end %>
    </table>
  </div>
</div> 
 