config/routes.rb
Querl::Application.routes.draw do
  resources :targets

  resources :target_lists

  resources :responses do
    collection do
      get 'export'
      get 'reports'
    end
  end

  resources :survey_items do
    collection do
      get 'add_to_survey'
    end
  end

  resources :user_roles

  resources :projects do
    collection do
      get 'show_users'
      get 'remove_user'
      get 'add_owner'
      get 'add_coder'
    end
  end
  resources :surveys do
    collection do
      get 'gather_response'
      get 'remove_survey_item'
      get 'preview'
      get 'move'
      get 'clone'
    end
  end
  
  resources :targets do
    collection do
      post 'import'
    end
  end

  devise_for :users

  root 'dashboard#index'

end

app/models/target_list.rb
class TargetList < ActiveRecord::Base
  
  belongs_to :project
  has_many :targets, -> { order('id') }, dependent: :destroy
  has_one :survey
end

app/controllers/target_lists_controller.rb
class TargetListsController < ApplicationController
  load_and_authorize_resource
  
  def index
    
  end
  
  def show
    @project = @target_list.project
    @current_items = @target_list.targets
  end  
  
  def new
    @target_list = TargetList.new
    @project = Project.find(params[:project_id])
  end
  
  def edit
    @project = Project.find(params[:project_id])
  end
  
  def create
    @target_list = TargetList.new(target_list_params)
    respond_to do |format|
      if @target_list.save
        format.html { redirect_to target_list_url(@target_list), notice: 'Target List was successfully created.' }
        format.json { render json: @target_list, status: :created, author: @target_list }
      else
        format.html { render action: "new" }
        format.json { render json: @target_list.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @target_list = TargetList.find(params[:id])
    
    respond_to do |format|
      if @target_list.update_attributes(params[:target_list])
        format.html { redirect_to root_url, notice: 'Target List was successfully updated.' }
        format.json { head :no_content }  
      else
        format.html { render action: "edit" }
        format.json { render json: @target_list.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @target_list = TargetList.find(params[:id])
    @project = @target_list.project
    @target_list.destroy
    
    respond_to do |format|
      format.html { redirect_to project_url(@project) }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target_list
      @target_list = TargetList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def target_list_params
      params.require(:target_list).permit!
    end
end

app/helpers/target_lists_helper.rb
module TargetListsHelper
end

app/views/target_lists/edit.html.erb
<h2>Edit Target List</h2>
<%= render :partial => 'shared/forms/target_list' %>

app/views/target_lists/new.html.erb
<div class="col-lg-12">
  <h2>New Target List</h2>
  <div class="row">
    <div class="well">
	  <%= render :partial => 'shared/forms/target_list' %>
    </div>
  </div>	
</div>

app/views/target_lists/show.html.erb
<% breadcrumb :target_list, @target_list %>

<h1><%= @project.name %>: <%= @target_list.name %></h1>

<% if @project.get_role(current_user) == 'owner' %>
<br />
<p><%= link_to('Rename Target List', edit_target_list_path(@target_list, :project_id => @project.id), :class => "action-edit") %></p>
<div class="col-lg-6">
  <h2>Batch Upload</h2>
  <p>Upload a CSV of Targets</p>
  <p>
    These are the fields to be populated:
	<ul>
	  <li>Name: header column as 'name' (no spaces or special characters, *required)</li>
	  <li>Display Text: header column as 'display_text'</li>
	  <li>Description: header column as 'description'</li>
	  <li>Link Text: header column as 'link_text' (*required)</li>
	</ul>
  </p>
  <p>
	  This is what the header row of your CSV file might look like:<br /><br />
	  <code>name,display_text,link_text,description</code>
  </p>
  <p>You do not need to include columns for non-required fields that you are not using.</p>
  <%= form_tag import_targets_path, :multipart => true, :class => "form-horizontal" do %>
    <fieldset>
      <legend>Targets for <%= @target_list.name %></legend>
  		<%= hidden_field_tag :target_list_id, @target_list.id %>
  		<div class="form-group"> 
  		  <label for="name" class="col-lg-2 control-label">File</label>
  		  <div class="col-lg-10">
  		    <%= file_field 'upload', 'datafile', :class => "form-control", accept: 'text/csv' %>
  		  </div>	
  		</div>
  		<%= submit_tag "Upload", :disable_with => 'Uploading...', :class => "btn btn-primary" %>
    </fieldset>	
  <% end %>
</div>

<div class="col-lg-12">
  <h2>Current Targets</h2>
  <p>Targets that are included in this Target List.</p>
  <div class="table-responsive">
    <table class="table table-striped table-hover ">
	  <tr>
	    <th>Name</th>
		<th>Display Text</th>
		<th>Link Text</th>
		<th>Description</th>
		<th></th>
	  </tr>
	  <% @current_items.each do |item| %>
	  <tr>
	    <td><%= item.name %></td>
		<td><%= item.display_text %></td>
		<td><%= item.link_text %></td>
		<td><%= item.description %></td>
		<td><%= link_to('Delete', target_path(item), :confirm => "Are you sure? This action cannot be undone.", :method => :delete) %></td>
	  </tr>
	  <% end %>
    </table>
  </div>
</div>
<% else %>
  You are not authorized to view this.
<% end %>