config/routes.rb
Querl::Application.routes.draw do
  resources :targets

  resources :target_lists

  resources :responses do
    collection do
      get 'export'
      get 'reports'
    end
  end

  resources :survey_items do
    collection do
      get 'add_to_survey'
    end
  end

  resources :user_roles

  resources :projects do
    collection do
      get 'show_users'
      get 'remove_user'
      get 'add_owner'
      get 'add_coder'
    end
  end
  resources :surveys do
    collection do
      get 'gather_response'
      get 'remove_survey_item'
      get 'preview'
      get 'move'
      get 'clone'
    end
  end
  
  resources :targets do
    collection do
      post 'import'
    end
  end

  devise_for :users

  root 'dashboard#index'

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :project
  has_and_belongs_to_many :survey_items, -> { order('survey_items_surveys.position') }
  has_many :responses
  belongs_to :target_list
  has_many :target_pools, -> { order('target_id') }
  
  def next_target(user)
    nxttar = ""
    behavior = self.behavior
    completed_targets = Array.new
    locked_target = self.target_pools.where(:user_id => user.id, :locked => true, :completed => false)
    
    if behavior == "Unicode (targets do not repeat across coders)"
      all_locked = Array.new
      self.target_pools.where(:locked => true, :completed => false).collect {|pool| all_locked << pool.target_id }
      self.target_pools.where(:locked => true, :completed => true).collect {|pool| completed_targets << pool.target_id }
    elsif behavior == "Multicode (all coders get all targets)"
      self.target_pools.where(:user_id => user.id, :locked => true, :completed => true).collect {|pool| completed_targets << pool.target_id }
    end  
    
    if self.target_pools.empty?
      TargetPool.create(:user_id => user.id, :target_id => self.target_list.targets.first.id, :survey_id => self.id, :locked => true, :completed => false)
      return self.target_list.targets.first
    elsif !locked_target[0].nil? 
      return Target.find(locked_target[0].target_id)  
    else  
      self.target_list.targets.each do |target|
        unless completed_targets.include?(target.id) || (!all_locked.nil? && all_locked.include?(target.id))
          nxttar = target
        end  
      end
      unless nxttar == ""
        TargetPool.create(:user_id => user.id, :target_id => nxttar.id, :survey_id => self.id, :locked => true, :completed => false)
      end  
      return nxttar  
    end  
  end 
  
  def clone_with_associations
      new_survey = self.dup
      new_survey.target_list = nil
      new_survey.behavior = nil
      new_survey.save
      #simple association
      new_survey.project = self.project
      new_survey.survey_items = self.survey_items
      new_survey
    end 
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  load_and_authorize_resource
  
  def index
    
  end
  
  def show
    @project = @survey.project
    @survey_items = @project.survey_items
    @current_items = @survey.survey_items
    @target_lists = @project.target_lists
    @owner_code = params[:owner_code]

    if @project.get_role(current_user) == 'coder' || @owner_code
      if @survey.target_list.nil? || @survey.target_list.blank?
        redirect_to project_url(@project), alert: 'No Target List Set!' and return
      end  
      if @survey.behavior.nil? || @survey.behavior.blank?
        redirect_to project_url(@project), alert: 'No Target Behavior Set!' and return
      end
      @next_target = @survey.next_target(current_user)
      if @next_target.blank?
        redirect_to project_url(@project), notice: 'Coding is Complete!'
      end  
    end  
    unless params[:answers].nil?
      @gather_response = params[:answers]
      p "gather response"
      p @gather_response
    end
    
    unless params[:gather_response].nil?
      redirect_to gather_response_surveys_url(:answers => params[:gather_response], :target_id => params[:target_id], :survey_id => @survey.id)
    end
  end  
  
  def new
    @survey = Survey.new
    @project = Project.find(params[:project_id])
  end
  
  def edit
    @project = Project.find(params[:project_id])
  end
  
  def create
    @survey = Survey.new(survey_params)
    respond_to do |format|
      if @survey.save
        format.html { redirect_to project_url(@survey.project), notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, author: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @survey = Survey.find(params[:id])
    unless params[:survey][:survey_item_ids].nil?
      all_items = SurveyItemsSurveys.all(:conditions => {:survey_id => @survey.id})
    end
    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        unless params[:survey][:survey_item_ids].nil?
          nil_items = SurveyItemsSurveys.all(:conditions => {:survey_id => @survey.id, :position => nil})
          i = 0
          if all_items.last.nil? || all_items.last.position.nil?
            pos = 1
          else  
            pos = all_items.last.position + 1
          end  
          while i < nil_items.length  do
             nil_items[i].position = pos
             nil_items[i].save
             i +=1
             pos +=1
          end 
          sorted = SurveyItemsSurveys.all(:conditions => {:survey_id => @survey.id}).sort_by { |hsh| hsh[:position] }
          j = 0
          pj = 1
          while j < sorted.length  do
             sorted[j].position = pj
             sorted[j].save
             j +=1
             pj +=1
          end  
        end
        unless params[:survey_id].nil?
          format.html { redirect_to survey_url(Survey.find(params[:id].to_i)), notice: 'Survey was successfully updated.' }
        else  
          format.html { redirect_to project_url(@survey.project), notice: 'Survey was successfully updated.' }
        end  
        format.json { head :no_content }  
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @survey = Survey.find(params[:id])
    @project = @survey.project
    @survey.destroy
    
    respond_to do |format|
      format.html { redirect_to project_url(@project) }
      format.json { head :no_content }
    end
  end
  
  def gather_response
    @survey = Survey.find(params[:survey_id].to_i)
    @project = @survey.project
    @survey_items = @project.survey_items
    @current_items = @survey.survey_items
    @target_lists = @project.target_lists
    @owner_code = params[:owner_code]
    
    @required_items = Array.new
    @survey.survey_items.where(:required => true).collect{|item| @required_items << item.id}
    
    req_error = false
    params[:answers].each_value do |value|
      if @required_items.include?(value["survey_item_id"].to_i)
        if SurveyItem.find(value["survey_item_id"].to_i).field_type == "Date"
          if value['response_text(1i)'].nil? || value['response_text(1i)'].blank?
            p "REQUIRED ERROR!"
            @next_target = Target.find(value["target_id"].to_i)
            req_error = true
          elsif value['response_text(2i)'].nil? || value['response_text(2i)'].blank?
            p "REQUIRED ERROR!"
            @next_target = Target.find(value["target_id"].to_i)
            req_error = true
          elsif value['response_text(3i)'].nil? || value['response_text(3i)'].blank?
            p "REQUIRED ERROR!"
            @next_target = Target.find(value["target_id"].to_i)
            req_error = true
          end      
        elsif value["response_text"].blank?
          p "REQUIRED ERROR!"
          @next_target = Target.find(value["target_id"].to_i)
          req_error = true
        end 
      end 
    end  
    
    if !req_error
      params[:answers].each_value do |value|
        if value["response_text"].class == Array
          value["response_text"] = value["response_text"].reject! { |r| r.empty? }.join(", ")
          response = Response.create(value)
        end
        
        if SurveyItem.find(value["survey_item_id"].to_i).field_type == "Date" && ((!value['response_text(1i)'].nil? && !value['response_text(1i)'].blank?) && (!value['response_text(2i)'].nil? && !value['response_text(2i)'].blank?) && (!value['response_text(3i)'].nil? && !value['response_text(3i)'].blank?))
          value['response_text'] = Date.new(value['response_text(1i)'].to_i, value['response_text(2i)'].to_i, value['response_text(3i)'].to_i).to_s
          value.delete('response_text(1i)')
          value.delete('response_text(2i)')
          value.delete('response_text(3i)')
          response = Response.create(value)
        end
      end 
      pool = TargetPool.first(:conditions => {:target_id => params[:target_id], :survey_id => @survey.id, :user_id => current_user.id, :locked => true, :completed => false})
      pool.completed = true
      pool.save
      params[:gather_response] = nil
    
      @next_target = @survey.next_target(current_user)
      p "next target"
      p @next_target
      if @next_target.blank?
        redirect_to project_url(@project), notice: 'Response was successfully recorded. Coding is Complete!'
      else
        if @project.get_role(current_user) == 'owner'
          redirect_to survey_url(@survey.id, :owner_code => true), notice: 'Response was successfully recorded.'
        else  
          redirect_to survey_url(@survey.id), notice: 'Response was successfully recorded.'
        end  
      end
    else
      @gather_response = params[:answers]
      if @project.get_role(current_user) == 'owner'
        redirect_to survey_url(@survey.id, :owner_code => true, :answers => @gather_response), alert: "Please enter required fields that are marked with *."
      else 
        redirect_to survey_url(@survey.id, :answers => @gather_response), alert: "Please enter required fields that are marked with *."
      end
      #format.html { render action: "show" }
      #format.json { render json: @survey.errors, status: :unprocessable_entity }
    end
    
  end
  
  def remove_survey_item
    @survey = Survey.find(params[:survey_id])
    @item_to_remove = SurveyItem.find(params[:survey_item_id])
    @current_survey_items = @survey.survey_items
    @survey.survey_items = @current_survey_items.delete_if {|item| item.id == @item_to_remove.id }
    
    redirect_to survey_url(@survey), notice: 'Survey item was removed.'
  end
  
  def preview
    @project = @survey.project
    @current_items = @survey.survey_items
    
  end
  
  def move
    survey = Survey.find(params[:survey_id])
    survey_items_surveys_item = SurveyItemsSurveys.first(:conditions => {:survey_id => survey.id, :survey_item_id => params[:survey_item_id]})
    if ["move_higher", "move_lower", "move_to_top", "move_to_bottom", "remove_from_list"].include?(params[:method]) and !survey_items_surveys_item.nil?
      survey_items_surveys_item.send(params[:method])
      if params[:method] == "remove_from_list"
        survey.survey_items = survey.survey_items.delete_if {|item| item.id == params[:survey_item_id].to_i }
      end  
    end
    redirect_to survey_url(survey)
  end
  
  def clone
    @survey = Survey.find(params[:survey_id])
    @new_survey = @survey.clone_with_associations
    redirect_to project_url(@survey.project), notice: 'Survey was cloned!'
  end  
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit!
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/edit.html.erb
<h2>Edit Survey</h2>
<%= render :partial => 'shared/forms/survey' %>

app/views/surveys/new.html.erb
<div class="col-lg-12">
  <h2>New Survey</h2>
  <div class="row">
    <div class="well">
	  <%= render :partial => 'shared/forms/survey' %>
    </div>
  </div>	
</div>

app/views/surveys/preview.html.erb
<h1><%= @survey.project.name %>: <%= @survey.name %></h1>

  <%= semantic_form_for :test, :html => { :class => "form-horizontal"} do |f| %>
  <fieldset>
    <legend><%= @survey.name %></legend>	    
	  <%= f.inputs do %>
  	    <% @current_items.each do |item| %>
  		  <% if item.field_type == "Label" %>
  		    <p><%= raw item.display_text %></p>
  		  <% else %>
			<%= f.semantic_fields_for "#{item.field_name}", :html => { :method => :get } do |fi| %>
			  <%= fi.input :survey_item_id, :as => :hidden, :input_html => { :value => item.id } %>	
			  <%= fi.input :survey_id, :as => :hidden, :input_html => { :value => @survey.id } %>  
	  	      <%= fi.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
	  		  <div class="form-group"> 
	  		    <label for="name" class="col-lg-2 control-label"><%= item.display_text.html_safe %></label>
	  		    <div class="col-lg-10">
				  <% if item.formtastic_field_map == "radio" || item.formtastic_field_map == "check_boxes" %>
				    <%= fi.input :response_text, :as => item.formtastic_field_map, :label => false , :collection => item.field_options.nil? ? '' : item.field_options.split(',') %>	
				  <% else %>
				    <%= fi.input :response_text, :as => item.formtastic_field_map, :label => false , :collection => item.field_options.nil? ? '' : item.field_options.split(','), :input_html => { :class => "form-control"}, :start_year => Time.now.year - 25, :end_year => Time.now.year + 10 %>	
				  <% end %>
	  		    </div>	
	  		  </div>  
		    <% end %>
		  <% end %>
		<% end %>
	  <% end %>	
  </fieldset>	
  <% end %>
  <%= button_to "Return to Project", project_path(@survey.project), :method => :get, :class => "btn btn-primary" %>

app/views/surveys/show.html.erb
<% breadcrumb :survey, @survey %>

<h1><%= @project.name %>: <%= @survey.name %></h1>

<% if @project.get_role(current_user) == 'owner' && !@owner_code %>	
<br />	
<p><%= link_to 'Rename Survey', edit_survey_path(@survey, :project_id => @project.id) %></p>
<div class="col-lg-12">
  <h2>Current Survey Items</h2>
  <p>Survey Items that are included in this Survey.</p>
  <div class="table-responsive">
    <table class="table table-striped table-hover ">
	  <tr>
	    <th>Name</th>
		<th>Description</th>
		<th>Actions</th>
	  </tr>
	  <% @current_items.each do |item| %>
	  <tr>
	    <td><%= item.field_name %></td>
		<td><%= item.field_type %></td>
		<td><%= link_to "&#8593;".html_safe, move_surveys_path(:method => 'move_higher', :survey_id => @survey.id, :survey_item_id => item.id)%>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "&#8595;".html_safe, move_surveys_path(:method => 'move_lower', :survey_id => @survey.id, :survey_item_id => item.id) %>&nbsp;&nbsp;&nbsp; | 
	    <%= link_to "Move to Top", move_surveys_path(:method => 'move_to_top', :survey_id => @survey.id, :survey_item_id => item.id)%> | <%= link_to "Move to Bottom", move_surveys_path(:method => 'move_to_bottom', :survey_id => @survey.id, :survey_item_id => item.id) %> | <%= link_to "Remove", move_surveys_path(:method => 'remove_from_list', :survey_id => @survey.id, :survey_item_id => item.id) %></td>
	  </tr>
	  <% end %>
    </table>
  </div>
</div>

<div class="col-lg-6">
  <h2>Available Survey Items</h2>
  <p><%= link_to "Create New Survey Item", new_survey_item_path(:project_id => @survey.project.id) %></p>
  <div class="row">
    <div class="well"> 
      <%= semantic_form_for @survey, :html => { :class => "form-horizontal"} do |f| %>
        <%= hidden_field :survey_id, @survey.id %>
		<fieldset>
          <legend>Manage Survey Items for <%= @survey.name %></legend>	    
  		  <%= f.inputs do %>
  		    <div class="form-group"> 
  		      <label for="name" class="col-lg-3 control-label">Survey Items</label>
  		      <div class="col-lg-9">
  		        <%= f.input :survey_items, :as => :check_boxes, :label => false, :collection => @survey_items, :member_label => Proc.new { |si| " #{si.display_text}" } %>
  		      </div>	
  		    </div>
  		  <% end %>
  		  <%= f.actions do %>
  		    <%= f.action :submit, :as => :button, :button_html => { :class => "btn btn-primary"} %>
  		  <% end %>
        </fieldset>	
      <% end %>
    </div>
  </div>
</div>

<div class="col-lg-6">
  <h2>Available Target Lists</h2>
  <p><%= link_to "Create New Target List", new_target_list_path(:project_id => @survey.project.id) %></p>
  <div class="row">
    <div class="well"> 
      <%= semantic_form_for @survey, :html => { :class => "form-horizontal"} do |f| %>
        <%= hidden_field :survey_id, @survey.id %>
		<fieldset>
          <legend>Manage Target Lists for <%= @survey.name %></legend>	    
  		  <%= f.inputs do %>
  		    <div class="form-group"> 
  		      <label for="name" class="col-lg-3 control-label">Target Lists</label>
  		      <div class="col-lg-9">
  		        <%= f.input :target_list_id, :as => :radio, :label => false, :collection => @target_lists, :member_label => Proc.new { |si| " #{si.name}" } %>
  		      </div>	
  		    </div>
  		    <div class="form-group"> 
  		      <label for="name" class="col-lg-3 control-label">Behavior</label>
  		      <div class="col-lg-9">
  		        <%= f.input :behavior, :as => :radio, :label => false, :collection => ["Multicode (all coders get all targets)", "Unicode (targets do not repeat across coders)"] %>
  		      </div>	
  		    </div>
  		  <% end %>
  		  <%= f.actions do %>
  		    <%= f.action :submit, :as => :button, :button_html => { :class => "btn btn-primary"} %>
  		  <% end %>
        </fieldset>	
      <% end %>
    </div>
  </div>
</div>

<% elsif @project.get_role(current_user) == 'coder' || @owner_code %>
  
<br />
  <%= semantic_form_for :gather_response, :html => { :class => "form-horizontal", :method => :get } do |f| %>
  <fieldset>
	<% if @next_target.display_text.nil? || @next_target.display_text.blank? %>
	  <legend>Target: <%= link_to @next_target.link_text, @next_target.link_text, :target => "_blank" %></legend>
	<% else %>  
      <legend>Target: <%= link_to @next_target.display_text, @next_target.link_text, :target => "_blank" %></legend>
    <% end %>
	  <%= hidden_field_tag :target_id, @next_target.id %>	    
	  <%= f.inputs do %>
  	    <% @current_items.each do |item| %>
  		  <% if item.field_type == "Label" %>
  		    <p><%= raw item.display_text %></p>
  		  <% else %>
			<%= f.semantic_fields_for "#{item.field_name}", :html => { :method => :get } do |fi| %>
			  <%= fi.input :survey_item_id, :as => :hidden, :input_html => { :value => item.id } %>	
			  <%= fi.input :survey_id, :as => :hidden, :input_html => { :value => @survey.id } %>  
	  	      <%= fi.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
			  <%= fi.input :target_id, :as => :hidden, :input_html => { :value => @next_target.id } %>
	  		  <div class="form-group"> 
	  		    <label for="name" class="col-lg-2 control-label"><%= item.display_text.html_safe %><%= item.required ? "*" : "" %></label>
	  		    <div class="col-lg-10">
				  <% if item.formtastic_field_map == "radio" || item.formtastic_field_map == "check_boxes" || item.formtastic_field_map ==  "select" %>
				    <% unless item.field_options.nil? %>
					  <% new_collection = Array.new %>
					  <% item.field_options.split(',').each do |option| %>
					    <% if !@gather_response.nil? && !@gather_response["#{item.field_name}"]["response_text"].nil? && @gather_response["#{item.field_name}"]["response_text"].include?(option) %>
						  <% if item.formtastic_field_map == "select" %>
						    <% new_collection << ["#{option}", "#{option}", {:selected => "selected"}] %>
						  <% else %>	
					        <% new_collection << ["#{option}", "#{option}", {:checked => "checked"}] %>
						  <% end %>	
						<% else %>
						  <% new_collection << ["#{option}", "#{option}"] %>  
						<% end %>  
					  <% end %>	
					<% end %>
					
				    <%= fi.input :response_text, :as => item.formtastic_field_map, :label => false, :collection => item.field_options.nil? ? '' : new_collection %>	
				  <% else %>
				    <% if item.formtastic_field_map ==  "date_select" %>
				      <%= fi.input :response_text, :as => item.formtastic_field_map, :label => false, :input_html => { :class => "form-control" }, :start_year => Time.now.year - 25, :end_year => Time.now.year + 10 %>	
					<% else %>
					  <%= fi.input :response_text, :as => item.formtastic_field_map, :label => false, :input_html => { :class => "form-control", :value => @gather_response.nil? ? "" : @gather_response["#{item.field_name}"]["response_text"]} %>	
					<% end %>    
				  <% end %>
	  		    </div>	
	  		  </div>  
		    <% end %>
		  <% end %>
		<% end %>
	  <% end %>	
	  <%= f.actions do %>
	    <%= f.action :submit, :as => :button, :label => "Submit", :button_html => { :class => "btn btn-primary"} %>
	  <% end %>
  </fieldset>	
  <% end %>

<% else %>
  You are not associated with this project.
<% end %>